import pandas as pd
from datetime import datetime
from docx import Document
from docx.shared import Pt, RGBColor
from docx.enum.text import WD_ALIGN_PARAGRAPH

def generate_report(narratives):
    doc = Document()

    # Title
    title = doc.add_heading("Ledger Discrepancy Narrator", 0)
    title.alignment = WD_ALIGN_PARAGRAPH.CENTER

    subtitle = doc.add_heading("Root-Cause Reconciliation Report", 2)
    subtitle.alignment = WD_ALIGN_PARAGRAPH.CENTER

    date_para = doc.add_paragraph(f"Generated: {datetime.now().strftime('%Y-%m-%d %H:%M')}")
    date_para.alignment = WD_ALIGN_PARAGRAPH.CENTER

    doc.add_paragraph("")

    # Summary Table
    doc.add_heading("Executive Summary", 1)
    doc.add_paragraph(f"Total Discrepancies Found: {len(narratives)}")

    type_counts = {}
    for n in narratives:
        t = n["issue"]["type"]
        type_counts[t] = type_counts.get(t, 0) + 1

    table = doc.add_table(rows=1, cols=2)
    table.style = "Table Grid"
    hdr = table.rows[0].cells
    hdr[0].text = "Discrepancy Type"
    hdr[1].text = "Count"

    for dtype, count in type_counts.items():
        row = table.add_row().cells
        row[0].text = dtype
        row[1].text = str(count)

    doc.add_paragraph("")

    # Detailed Findings
    doc.add_heading("Detailed Findings", 1)

    for i, n in enumerate(narratives, 1):
        issue = n["issue"]
        narrative = n["narrative"]

        doc.add_heading(f"Issue #{i}: {issue['type']} — {issue['transaction_id']}", 2)

        detail_table = doc.add_table(rows=3, cols=2)
        detail_table.style = "Table Grid"

        detail_table.rows[0].cells[0].text = "System"
        detail_table.rows[0].cells[1].text = issue["system"]

        detail_table.rows[1].cells[0].text = "Transaction ID"
        detail_table.rows[1].cells[1].text = issue["transaction_id"]

        detail_table.rows[2].cells[0].text = "Raw Detail"
        detail_table.rows[2].cells[1].text = issue["detail"]

        doc.add_paragraph("")
        doc.add_heading("AI Root-Cause Explanation:", 3)
        doc.add_paragraph(narrative)
        doc.add_paragraph("")

    # Footer
    doc.add_paragraph("─" * 60)
    footer = doc.add_paragraph("This report was generated by Ledger Discrepancy Narrator | Generative AI Financial Reconciliation Tool | 2026")
    footer.alignment = WD_ALIGN_PARAGRAPH.CENTER

    filename = f"reports/Reconciliation_Report_{datetime.now().strftime('%Y%m%d_%H%M')}.docx"
    doc.save(filename)
    print(f"\nReport saved: {filename}")
    return filename